"""
Django settings for webcaf project.

Generated by 'django-admin startproject' using Django 5.1.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

from csp.constants import NONCE, SELF
from environ import Env

env = Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent

Env.read_env(os.path.join(BASE_DIR, ".env"))

DEBUG = env.bool("DEBUG")
if DEBUG:
    # Use dotenv for debug environments
    from dotenv import load_dotenv

    load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY: str = env.str("SECRET_KEY", default="not_set")  # type: ignore

if SECRET_KEY == "not_set" and not DEBUG:  # pragma: allowlist secret
    raise Exception("SECRET_KEY must be set in production")

APPEND_SLASH = True
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["*"])
ENVIRONMENT = env.str("ENVIRONMENT", default=None)

X_FRAME_OPTIONS = "SAMEORIGIN"

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "govuk_frontend_django",
    "webcaf.webcaf.apps.WebcafConfig",
    "csp",
    "django_otp",
    "django_otp.plugins.otp_email",
    "mozilla_django_oidc",
    "simple_history",
    "axes",
]

MIDDLEWARE = [
    "csp.middleware.CSPMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "webcaf.middleware.RequestLoggingMiddleware",
    "axes.middleware.AxesMiddleware",
    "django_otp.middleware.OTPMiddleware",
    "webcaf.session.CafSessionTimeoutMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "webcaf.auth.LoginRequiredMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
]

ROOT_URLCONF = "webcaf.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "webcaf", "templates"), os.path.join(BASE_DIR, "webcaf", "templates", "caf")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "webcaf.context_processors.variable_page_content",
            ],
        },
    },
]

WSGI_APPLICATION = "webcaf.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

if "RDS_DB_NAME" in os.environ:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ["RDS_DB_NAME"],
            "USER": os.environ["RDS_USERNAME"],
            "PASSWORD": os.environ["RDS_PASSWORD"],
            "HOST": os.environ["RDS_HOST"],
            "PORT": os.environ["RDS_PORT"],
            "OPTIONS": {
                "connect_timeout": 5,
            },
        }
    }
else:
    DATABASES = {
        "default": env.db_url(default="postgresql:///webcaf"),  # type: ignore
    }

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "webcaf", "static"),
]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
STATIC_URL = "/assets/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")
# Django Whitenoise Configuration
WHITENOISE_SKIP_COMPRESS_EXTENSIONS = [".map"]
WHITENOISE_ALLOW_ALL_ORIGINS = False
if not DEBUG:
    WHITENOISE_AUTOREFRESH = False  # Don't auto-reload in production
    WHITENOISE_MAX_AGE = 86400  # 24 hours (in seconds)
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

# Content Security Policy: only allow images, stylesheets and scripts from the
# same origin as the HTML
CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        "connect-src": (
            SELF,
            "https://*.google-analytics.com",
            "https://*.analytics.google.com",
            "https://*.googletagmanager.com",
        ),
        "form-action": (SELF,),
        "frame-ancestors": (SELF,),
        "frame-src": (SELF, NONCE, "https://www.googletagmanager.com"),
        "img-src": (SELF, NONCE, "data:"),
        "script-src": (
            SELF,
            NONCE,
            "sha256-nBhTljJHpMrd9MOPzdAm2s1BkTJWObIEdVxg/bet7PE=",  # pragma: allowlist secret
            "https://*.googletagmanager.com",
        ),
        "style-src": (
            SELF,
            NONCE,
        ),
    }
}

# Respect proxy headers when running behind a TLS-terminating ingress.
USE_X_FORWARDED_HOST = env.bool("USE_X_FORWARDED_HOST", default=False)
if USE_X_FORWARDED_HOST:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# If we want to test CSP breaches we need to set a fake reporting URL, so the tests
# check if it's been called.
if "TEST_CSP" in os.environ:
    CSP_REPORT_URI = "/csp-report"  # The URI doesn't exist but is intercepted by the test suite

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-gb"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

FRAMEWORK_PATH = os.path.join(BASE_DIR, "..", "frameworks", "cyber-assessment-framework-v3.2.yaml")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "request_context": {
            "()": "webcaf.logging_filters.RequestLogFilter",
        },
    },
    "formatters": {
        "verbose": {
            "format": "[%(asctime)s] [%(process)d:%(threadName)s] [user=%(user_id)s sess=%(session_id)s] [%(levelname)s] [%(name)s] %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S %z",
        },
    },
    "handlers": {
        "console": {
            "level": ("INFO" if not DEBUG else "DEBUG"),
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            "filters": ["request_context"],
        },
    },
    "loggers": {
        "": {
            "level": ("INFO" if not DEBUG else "DEBUG"),
            "handlers": ["console"],
            "propagate": True,
        },
    },
}

SSO_MODE = env.str("SSO_MODE", "external").lower()  # external, dex, local, none

if SSO_MODE == "external":
    OIDC_RP_CLIENT_ID = env.str("OIDC_RP_CLIENT_ID")
    OIDC_RP_CLIENT_SECRET = env.str("OIDC_RP_CLIENT_SECRET")  # pragma: allowlist secret
    OIDC_OP_AUTHORIZATION_ENDPOINT = env.str("OIDC_OP_AUTHORIZATION_ENDPOINT")
    OIDC_OP_TOKEN_ENDPOINT = env.str("OIDC_OP_TOKEN_ENDPOINT")
    OIDC_OP_USER_ENDPOINT = env.str("OIDC_OP_USER_ENDPOINT")
    OIDC_OP_JWKS_ENDPOINT = env.str("OIDC_OP_JWKS_ENDPOINT")
    OIDC_OP_LOGOUT_ENDPOINT = env.str("OIDC_OP_LOGOUT_ENDPOINT")
    OIDC_STORE_ID_TOKEN = True
    OIDC_STORE_ACCESS_TOKEN = True
    LOGOUT_REDIRECT_URL = env.str("LOGOUT_REDIRECT_URL")
    NOTIFY_API_KEY = env.str("NOTIFY_API_KEY", "")
    NOTIFY_OTP_TEMPLATE_ID = env.str("NOTIFY_OTP_TEMPLATE_ID", "")
    ENABLED_2FA = env.bool("ENABLED_2FA", default=True)
elif SSO_MODE == "none":
    # Local Django auth only; do not configure OIDC endpoints.
    LOGIN_URL = env.str("LOGIN_URL", "/admin/login/")
    LOGOUT_REDIRECT_URL = env.str("LOGOUT_REDIRECT_URL", "/")
    OIDC_RP_CLIENT_ID = ""
    OIDC_RP_CLIENT_SECRET = ""
    OIDC_OP_AUTHORIZATION_ENDPOINT = ""
    OIDC_OP_TOKEN_ENDPOINT = ""
    OIDC_OP_USER_ENDPOINT = ""
    OIDC_OP_JWKS_ENDPOINT = ""
    OIDC_OP_LOGOUT_ENDPOINT = ""
    ENABLED_2FA = False
else:
    sso_host = "dex" if SSO_MODE == "dex" else "localhost"
    OIDC_RP_CLIENT_ID = "my-django-app"
    OIDC_RP_CLIENT_SECRET = "my-django-secret"  # pragma: allowlist secret
    # We need to override the host to docker compose container name
    # When we run behave tests in docker
    OIDC_OP_AUTHORIZATION_ENDPOINT = f"http://{env.str('OVERRIDE_SSO_HOST', 'localhost')}:5556/auth"
    OIDC_OP_TOKEN_ENDPOINT = f"http://{sso_host}:5556/token"
    OIDC_OP_USER_ENDPOINT = f"http://{sso_host}:5556/userinfo"
    OIDC_OP_JWKS_ENDPOINT = f"http://{sso_host}:5556/keys"
    OIDC_STORE_ID_TOKEN = True
    OIDC_STORE_ACCESS_TOKEN = True
    OIDC_OP_LOGOUT_ENDPOINT = f"http://{env.str('OVERRIDE_SSO_HOST', 'localhost')}:5556/auth/logout"
    LOGOUT_REDIRECT_URL = f"http://{env.str('OVERRIDE_APP_HOST', 'localhost')}:8010/"
    # if we enable 2fa locally for testing this ensures we capture the token in the local console
    # rather than attempting to a send gov notify email
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    ENABLED_2FA = False

if SSO_MODE == "none":
    AUTHENTICATION_BACKENDS = (
        "axes.backends.AxesStandaloneBackend",
        "django.contrib.auth.backends.ModelBackend",
    )
else:
    AUTHENTICATION_BACKENDS = (
        "webcaf.auth.OIDCBackend",
        "axes.backends.AxesStandaloneBackend",
        "django.contrib.auth.backends.ModelBackend",
    )

# Confirmation email template ID
# System will not send a confirmation email if this is not set
NOTIFY_CONFIRMATION_TEMPLATE_ID = env.str("NOTIFY_CONFIRMATION_TEMPLATE_ID", "")

OIDC_RP_SCOPES = env.str("OIDC_RP_SCOPES", "openid email profile")
OIDC_RP_SIGN_ALGO = env.str("OIDC_RP_SIGN_ALGO", "RS256")
OIDC_TOKEN_AUTH_METHOD = env.str("OIDC_TOKEN_AUTH_METHOD", "client_secret_basic")
OIDC_CLIENT_ASSERTION_PRIVATE_KEY = env.str("OIDC_CLIENT_ASSERTION_PRIVATE_KEY", default="")
OIDC_CLIENT_ASSERTION_KID = env.str("OIDC_CLIENT_ASSERTION_KID", default="")
OIDC_CLIENT_ASSERTION_ALG = env.str("OIDC_CLIENT_ASSERTION_ALG", default="RS256")
OIDC_USER_AGENT = env.str("OIDC_USER_AGENT", default="webcaf/1.0")
OIDC_RELAX_CLAIMS = env.bool("OIDC_RELAX_CLAIMS", default=False)
OIDC_DEBUG_CLAIMS = env.bool("OIDC_DEBUG_CLAIMS", default=False)
if DEBUG:
    OIDC_VERIFY_SSL = False

ALLOW_LOGOUT_GET_METHOD = True
LOGIN_REDIRECT_URL = "/my-account/"

if not DEBUG:
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = True
    CSRF_TRUSTED_ORIGINS = [f"https://{os.environ.get('DOMAIN_NAME', 'localhost')}"]
    # CSRF_FAILURE_VIEW = "webcaf.request.views.csrf_failure_view"
    SESSION_COOKIE_SECURE = True

# Admin site login attempt limit

AXES_LOCKOUT_PARAMETERS = ["username"]

# Optional: lockout time in hours
AXES_COOLOFF_TIME = 1
AXES_FAILURE_LIMIT = 5
AXES_LOCKOUT_TEMPLATE = "429.html"

SENTRY_DSN = env.str("SENTRY_DSN", default=None)
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.types import SamplingContext

    def traces_sampler(sampling_context: SamplingContext) -> float:
        """
        Sets up custom sampling rate for specific scenarios.

        :param: sampling_context: Internal interface from Sentry for sampling callback
        :return: sampling rate
        """
        # Disable health Check trace sampling
        if (
            sampling_context["transaction_context"]["name"] == "generic WSGI request"
            and sampling_context["wsgi_environ"]["HTTP_USER_AGENT"] == "ELB-HealthChecker/2.0"
        ):
            return 0.0
        else:
            # Any other trace sampling rate - prod: 100%, non-prod: 20%
            return 0.2 if ENVIRONMENT != "prod" else 1.0

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=ENVIRONMENT,
        traces_sampler=traces_sampler,
    )

# sets session timeout at 90 minutes
USER_IDLE_TIMEOUT = 90 * 60
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
